version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bank
    volumes:
       - postgres:/var/lib/postgresql/data
  api:
    container_name: api
    build: 
      context: api
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file:
      - api/.env
  front:
    container_name: front
    build: 
      context: front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
      - api


volumes:
  postgres:
    name: db